variables:
    GIT_SUBMODULE_STRATEGY: recursive
    LIVE_PLUGINS: /home/krafittl/public_html/simonkraft/wp-content/plugins
    LIVE_THEMES: /home/krafittl/public_html/simonkraft/wp-content/themes

before_script:
    - git clone --branch=master --depth=1 --quiet git@git.simonkraft.com:meta/deploy-script.git
    - chmod +x deploy-script/*.sh

stages:
    - test
    - production

# test:
#     stage: test
    
#     script:
#         - cd deploy-script
#         - ./deploy.sh -u $SSH_USER_TEST -d $DEPLOY_PATH -h $DEPLOY_SERVER
    
#     only:
#         - master
    
#     variables:
#         DEPLOY_PATH: ${WD50_PATH_TEST_PLUGINS}/rh-dummy
#         DEPLOY_SERVER: northstar.li
        
#         # GitLab group variables:
#         # - SSH_USER_TEST

production:
    stage: production
    
    script:
        - cd deploy-script
        - ./deploy.sh -u krafittl -d $DEPLOY_PATH -h $DEPLOY_SERVER --theme
    
    only:
        - master

    variables:
        DEPLOY_PATH: $LIVE_THEMES
        DEPLOY_SERVER: vsa-kigoru.cyon.net
        
        # GitLab group variables:
        # - 
