variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - git clone --branch=master --depth=1 --quiet git@git.simonkraft.com:meta/deploy-script.git
    - chmod +x deploy-script/*.sh

stages:
    - production

production:
    stage: production
    
    script:
        - cd deploy-script
        - ./deploy.sh -u simonkraft -d $DEPLOY_PATH -h $DEPLOY_SERVER --theme
    
    only:
        - master

    variables:
        DEPLOY_PATH: /sites/login.simonkraft.de/files/wp-content/themes/meitner
        DEPLOY_SERVER: kronos.simonkraft.com